version: "3"

services:
  app:
    build: .
    command: ./gradlew bootRun --args='--spring.profiles.active=${PROFILE}'
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    envirenment:
      - PROFILE